version: '3'

services:
  # Tempo server for distributed tracing
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"   # tempo API
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3200/ready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - tempo

  # Sample application generating traces
  trace-generator:
    image: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen:latest
    command: [ "traces", "--otlp-endpoint=tempo:4317", "--otlp-insecure", "--rate=1", "--service=example-service" ]
    depends_on:
      tempo:
        condition: service_healthy

  # Tempo MCP server
  tempo-mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TEMPO_URL=http://tempo:3200
    depends_on:
      tempo:
        condition: service_healthy 